# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170820_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['path']},
        ),
    ]
